[project]
name = "uvisbox"
version = "0.1.0"
description = "Uncertainty Visualization Toolbox with care from SCI Utah"
authors = [
    {name = "Timbwaoga Aime Judicael Ouermi",email = "timbwaoga.ouermi@utah.edu"},
    {name = "Jixian Li",email = "jixianli@sci.utah.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "numpy (>=2.0,<3.0.0)",
    "scipy (>=1.16.1,<2.0.0)",
    "matplotlib (>=3.10.5,<4.0.0)",
    "scikit-learn (>=1.7.1,<2.0.0)",
    "scikit-image (>=0.25.2,<0.26.0)",
    "pyvista (>=0.46.3,<0.47.0)",
    "basemap (>=2.0.0,<2.1.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
netcdf4 = "^1.7.3"
pytest = "^8.4.2"
black = "^25.9.0"
isort = "^7.0.0"
h5py = "^3.15.1"

