name: Build and deploy Sphinx documentation

on:
  pull_request:
    paths:
      - ".github/workflows/sphinx-gh-pages.yml"
      - "docs/**"
      - "examples/**"
      - "uvisbox/**"
      - "environment.yml"
      - "pyproject.toml"
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create Conda environment
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: uvisbox
          environment-file: environment.yml
          miniforge-version: latest
          python-version: "3.11"
          conda-solver: libmamba

      - name: Build documentation strictly
        env:
          MPLBACKEND: Agg
          PYVISTA_OFF_SCREEN: "true"
          SPHINX_BUILD: "1"
        run: python docs/build_docs.py

      - name: Upload documentation artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
